version: '3.8'

services:
  # --- Serviço do Frontend (Angular) ---
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: taskmanager-frontend
    # CRÍTICO: Mapeamento de Portas.
    # A primeira porta (4200) é a porta do SEU HOST (seu computador).
    # A segunda porta (4200) é a porta interna do container (onde o http-server roda).
    ports:
      - "4200:4200"
    depends_on:
      - backend

  # --- Serviço do Backend (Spring Boot) ---
  backend:
    # Assumindo que o código Spring Boot está na pasta 'backend'
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: taskmanager-backend
    # CRÍTICO: Mapeamento de Portas para o Backend (API)
    # 8080 do host mapeado para 8080 do container.
    ports:
      - "8080:8080"
    environment:
      # Variáveis de ambiente para o Spring Boot se conectar ao PostgreSQL
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/taskdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db

  # --- Serviço do Banco de Dados (PostgreSQL) ---
  db:
    image: postgres:14-alpine
    container_name: taskmanager-db
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      # Persistência dos dados
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
