version: '3.8'

services:
  database:
    image: postgres:13
    container_name: task-manager-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_manager_db
    ports:
      - "5432:5432"
    volumes:
      - ./docker/data/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d task_manager_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: task-manager-backend
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: task-manager-frontend
    ports:
      - "4200:80"  # Mapeia a porta local 4200 para a porta 80 do contêiner
    environment:
      API_URL: http://backend:8080
    depends_on:
      - backend